//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsTheWeather.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhatsTheWeather.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dataservice.accuweather.com/currentconditions/v1/{LOCATION_KEY}?apikey={API_KEY}.
        /// </summary>
        internal static string AccuWeatherAPI {
            get {
                return ResourceManager.GetString("AccuWeatherAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dataservice.accuweather.com/locations/v1/postalcodes/search?apikey={API_KEY}&amp;q={POSTAL_CODE}&amp;language=en-us.
        /// </summary>
        internal static string AccuWeatherLocationAPI {
            get {
                return ResourceManager.GetString("AccuWeatherLocationAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openweathermap.org/data/2.5/weather?zip={POSTAL_CODE},us&amp;units=imperial&amp;appid={API_KEY}.
        /// </summary>
        internal static string OpenWeatherAPI {
            get {
                return ResourceManager.GetString("OpenWeatherAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.openweathermap.org/geo/1.0/zip?zip={POSTAL_CODE}&amp;appid={API_KEY}.
        /// </summary>
        internal static string OpenWeatherGeocodeAPI {
            get {
                return ResourceManager.GetString("OpenWeatherGeocodeAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wh@tsTh3We@th3rR0cks7h3W04ld9999.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R0cks7h3W04ld99.
        /// </summary>
        internal static string Phrase {
            get {
                return ResourceManager.GetString("Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccuWeatherApiKey.
        /// </summary>
        internal static string Settings_AccuWeatherApiKey {
            get {
                return ResourceManager.GetString("Settings_AccuWeatherApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenWeatherApiKey.
        /// </summary>
        internal static string Settings_OpenWeatherApiKey {
            get {
                return ResourceManager.GetString("Settings_OpenWeatherApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalCode.
        /// </summary>
        internal static string Settings_PostalCode {
            get {
                return ResourceManager.GetString("Settings_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherSelection.
        /// </summary>
        internal static string Settings_SelectedWeatherProvider {
            get {
                return ResourceManager.GetString("Settings_SelectedWeatherProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualCrossingApiKey.
        /// </summary>
        internal static string Settings_VisualCrossingApiKey {
            get {
                return ResourceManager.GetString("Settings_VisualCrossingApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherApiApiKey.
        /// </summary>
        internal static string Settings_WeatherApiApiKey {
            get {
                return ResourceManager.GetString("Settings_WeatherApiApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherBitApiKey.
        /// </summary>
        internal static string Settings_WeatherBitApiKey {
            get {
                return ResourceManager.GetString("Settings_WeatherBitApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherHourlyPollTimer.
        /// </summary>
        internal static string Settings_WeatherHourlyPollTimer {
            get {
                return ResourceManager.GetString("Settings_WeatherHourlyPollTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherShowBalloon.
        /// </summary>
        internal static string Settings_WeatherShowBalloon {
            get {
                return ResourceManager.GetString("Settings_WeatherShowBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherUnlockedAppId.
        /// </summary>
        internal static string Settings_WeatherUnlockedAppId {
            get {
                return ResourceManager.GetString("Settings_WeatherUnlockedAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherUnlockedAppKey.
        /// </summary>
        internal static string Settings_WeatherUnlockedAppKey {
            get {
                return ResourceManager.GetString("Settings_WeatherUnlockedAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherZipCode.
        /// </summary>
        internal static string Settings_WeatherZipCode {
            get {
                return ResourceManager.GetString("Settings_WeatherZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {API_KEY}.
        /// </summary>
        internal static string Url_Api_Key {
            get {
                return ResourceManager.GetString("Url_Api_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {POSTAL_CODE}.
        /// </summary>
        internal static string Url_Postal_Code {
            get {
                return ResourceManager.GetString("Url_Postal_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/{POSTAL_CODE}/today?include=fcst&amp;key={API_KEY}&amp;contentType=json.
        /// </summary>
        internal static string VisualCrossingAPI {
            get {
                return ResourceManager.GetString("VisualCrossingAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.weatherapi.com/v1/current.json?key={API_KEY}&amp;q={POSTAL_CODE}&amp;aqi=no.
        /// </summary>
        internal static string WeatherAPI {
            get {
                return ResourceManager.GetString("WeatherAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.weatherbit.io/v2.0/current?postal_code={POSTAL_CODE}&amp;key={API_KEY}.
        /// </summary>
        internal static string WeatherBitAPI {
            get {
                return ResourceManager.GetString("WeatherBitAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccuWeather is enabled but missing the API Key. Please enter an API Key!.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_AccuWeather_API_Key_Missing {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_AccuWeather_API_Key_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Weather is enabled but missing the API Key. Please enter an API Key!.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_Open_Weather_API_Key_Missing {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_Open_Weather_API_Key_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Weather is no longer eanbled. The API Key will be deleted!
        ///Are you sure you want to continue?.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_OpenWeather {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_OpenWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccuWeather is no longer eanbled. The API Key will be deleted!
        ///Are you sure you want to continue?.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_VerifyAccuWeather {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_VerifyAccuWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Crossing is enabled but missing the API Key. Please enter an API Key!.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_Visual_Crossing_API_Key_Missing {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_Visual_Crossing_API_Key_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Crossing is no longer eanbled. The API Key will be deleted!
        ///Are you sure you want to continue?.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_VisualCrossing {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_VisualCrossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_Warning {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather API is enabled but missing the API Key. Please enter an API Key!.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_Weather_API_API_Key_Missing {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_Weather_API_API_Key_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Unlocked is enabled but missing the APP ID and/or the APP Key. Please enter an APP ID and/or APP Key!.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_Weather_Unlocked_API_Key_Missing {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_Weather_Unlocked_API_Key_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather API is no longer eanbled. The API Key will be deleted!
        ///Are you sure you want to continue?.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_WeatherApi {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_WeatherApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherBit.io is no longer eanbled. The API Key will be deleted!
        ///Are you sure you want to continue?.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_WeatherBit {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_WeatherBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherBit.io is enabled but missing the API Key. Please enter an API Key!.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_WeatherBit_API_Key_Missing {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_WeatherBit_API_Key_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Unlocked is no longer eanbled. The API Key will be deleted!
        ///Are you sure you want to continue?.
        /// </summary>
        internal static string WeatherServicesWindow_VerifySettingChanges_WeatherUnlocked {
            get {
                return ResourceManager.GetString("WeatherServicesWindow_VerifySettingChanges_WeatherUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.weatherunlocked.com/api/current/us.{POSTAL_CODE}?app_id={APP_ID}&amp;app_key={APP_KEY}.
        /// </summary>
        internal static string WeatherUnlockedAPI {
            get {
                return ResourceManager.GetString("WeatherUnlockedAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string WhatsTheWeatherMainWindow_InvokePollingProcess_Start {
            get {
                return ResourceManager.GetString("WhatsTheWeatherMainWindow_InvokePollingProcess_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string WhatsTheWeatherMainWindow_InvokePollingProcess_Stop {
            get {
                return ResourceManager.GetString("WhatsTheWeatherMainWindow_InvokePollingProcess_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid zip code!.
        /// </summary>
        internal static string WhatsTheWeatherMainWindow_VerifyValues_Please_enter_a_valid_zip_code_ {
            get {
                return ResourceManager.GetString("WhatsTheWeatherMainWindow_VerifyValues_Please_enter_a_valid_zip_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid weather provider!.
        /// </summary>
        internal static string WhatsTheWeatherMainWindow_VerifyValues_Please_select_a_valid_weather_provider_ {
            get {
                return ResourceManager.GetString("WhatsTheWeatherMainWindow_VerifyValues_Please_select_a_valid_weather_provider_", resourceCulture);
            }
        }
    }
}
